### ISSUE TITLE
Error occurs in Angular when after updating to v1.6.0

### ISSUE THREAD

**Issue by CraigLee17** [nagix/chartjs-plugin-streaming#44]
```
core.js:1598 ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'removeEventListener' of null
TypeError: Cannot read property 'removeEventListener' of null
    at Object.destroy (chartjs-plugin-streaming.js:874)
    at Object.notify (core.plugins.js:109)
    at Chart.destroy (core.controller.js:767)
    at BaseChartDirective.push../node_modules/ng2-charts/charts/charts.js.BaseChartDirective.ngOnDestroy (charts.js:51)
    at callProviderLifecycles (core.js:10420)
    at callElementProvidersLifecycles (core.js:10388)
    at callLifecycleHooksChildrenFirst (core.js:10378)
    at destroyView (core.js:11442)
    at callViewAction (core.js:11568)
    at execComponentViewsAction (core.js:11490)
    at Object.destroy (chartjs-plugin-streaming.js:874)
    at Object.notify (core.plugins.js:109)
    at Chart.destroy (core.controller.js:767)
    at BaseChartDirective.push../node_modules/ng2-charts/charts/charts.js.BaseChartDirective.ngOnDestroy (charts.js:51)
    at callProviderLifecycles (core.js:10420)
    at callElementProvidersLifecycles (core.js:10388)
    at callLifecycleHooksChildrenFirst (core.js:10378)
    at destroyView (core.js:11442)
    at callViewAction (core.js:11568)
    at execComponentViewsAction (core.js:11490)
    at resolvePromise (zone.js:814)
    at resolvePromise (zone.js:771)
    at zone.js:873
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:421)
    at Object.onInvokeTask (core.js:4053)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:420)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.runTask (zone.js:188)
    at drainMicroTaskQueue (zone.js:595)
    at ZoneTask.push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask [as invoke] (zone.js:500)
    at invokeTask (zone.js:1540)
```
It works fine in the chart view. The error occurs when I leave the chart view.

**Comment by shincysl** [comment]
Same here.  See: https://github.com/chartjs/Chart.js/blob/master/src/core/core.controller.js?utf8=%E2%9C%93#L773

```
			if (canvas) {
				me.unbindEvents();
				helpers.canvas.clear(me);
				platform.releaseContext(me.ctx);
				me.canvas = null;
				me.ctx = null;
			}

			plugins.notify(me, 'destroy');
```

Chart.js sets canvas to null before firing 'destroy' event. canvas is not available in destroy event.

**Comment by nagix** [comment]
Thank you for reporting the issue. This was fixed by 56b5902 and 5f39622.
